import { useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Printer } from 'lucide-react'
import { ArgusMark } from '../components/ArgusMark'
import { useAuth } from '../context/AuthContext'
import { useAuthedQuery } from '../hooks/useAuthedQuery'
import * as api from '../lib/api'
import { formatCount, formatUtcDateTime, isoHoursAgo } from '../lib/format'
import { tacticLabel, tacticRank } from '../lib/mitre'
import { scoreSeverity, type Severity } from '../lib/severity'

const TEMPLATES = [
  {
    id: 'executive',
    name: 'Executive summary',
    description: 'Posture snapshot: alerts, cases, detections — for leadership.',
  },
  {
    id: 'incident',
    name: 'Incident report',
    description: 'One case end to end: evidence, techniques, analyst notes.',
  },
  {
    id: 'compliance',
    name: 'ATT&CK coverage',
    description: 'Detection coverage per tactic against the full catalog.',
  },
] as const
type TemplateId = (typeof TEMPLATES)[number]['id']

const SEV_HEX: Record<Severity, string> = {
  critical: '#D14B4B',
  high: '#C97F2F',
  medium: '#A38C1F',
  low: '#1D9E75',
  info: '#5A76C9',
}

export function Reports() {
  const [params] = useSearchParams()
  const [template, setTemplate] = useState<TemplateId>(
    (params.get('template') as TemplateId) || 'executive',
  )
  const [caseId, setCaseId] = useState<number | null>(Number(params.get('case')) || null)

  const cases = useAuthedQuery(['cases', 'all'], (t) => api.listCases(t, { limit: 200 }))

  return (
    <div className="space-y-4 p-6">
      <div className="flex items-baseline justify-between print:hidden">
        <h1 className="text-page-title">Reports</h1>
        <button
          type="button"
          onClick={() => window.print()}
          className="flex items-center gap-1.5 rounded-control bg-accent px-3 py-1.5 text-label font-medium text-(--bg-base) transition-colors duration-120 hover:bg-accent-dim"
        >
          <Printer size={13} strokeWidth={1.5} />
          Export to PDF
        </button>
      </div>

      <div className="flex flex-wrap gap-3 print:hidden">
        {TEMPLATES.map((t) => (
          <button
            key={t.id}
            type="button"
            onClick={() => setTemplate(t.id)}
            className={`w-60 rounded-card border-[0.5px] p-3.5 text-left transition-colors duration-120 ${
              template === t.id ? 'border-accent bg-accent-bg/30' : 'border-subtle bg-elevated hover:bg-hover'
            }`}
          >
            <div className="text-label font-medium text-primary">{t.name}</div>
            <div className="mt-0.5 text-label text-secondary">{t.description}</div>
          </button>
        ))}
        {template === 'incident' && (
          <select
            value={caseId ?? ''}
            onChange={(e) => setCaseId(Number(e.target.value) || null)}
            className="self-start rounded-control border-[0.5px] border-subtle bg-elevated px-3 py-2 text-label text-primary outline-none"
          >
            <option value="">Select a case…</option>
            {cases.data?.items.map((c) => (
              <option key={c.id} value={c.id}>
                #{c.id} — {c.title}
              </option>
            ))}
          </select>
        )}
      </div>

      {/* The sheet is the only thing the print stylesheet keeps */}
      <div className="report-sheet mx-auto max-w-3xl overflow-hidden rounded-card bg-white text-[#241b3d] shadow-lg shadow-black/30">
        <ReportCover template={template} />
        <div className="px-8 py-6">
          {template === 'executive' && <ExecutiveReport />}
          {template === 'incident' &&
            (caseId ? (
              <IncidentReport caseId={caseId} />
            ) : (
              <p className="py-8 text-center text-[13px] text-[#6b6485]">
                Pick a case above to build the incident report.
              </p>
            ))}
          {template === 'compliance' && <ComplianceReport />}
        </div>
        <footer className="border-t border-[#e5e1f0] px-8 py-3 text-[10px] text-[#6b6485]">
          Generated by ARGUS · {formatUtcDateTime(Date.now())} · internal use
        </footer>
      </div>
    </div>
  )
}

function ReportCover({ template }: { template: TemplateId }) {
  const { tenantSlug, email } = useAuth()
  const title = TEMPLATES.find((t) => t.id === template)!.name
  return (
    <div
      className="flex items-center gap-4 px-8 py-6"
      style={{ background: '#160E28', printColorAdjust: 'exact', WebkitPrintColorAdjust: 'exact' }}
    >
      <ArgusMark size={44} />
      <div>
        <div className="text-[11px] tracking-[0.24em] text-[#B8B5C9]">ARGUS</div>
        <h2 className="text-[20px] font-medium text-[#EDEBF5]">{title}</h2>
        <div className="mt-0.5 font-mono text-[11px] text-[#A79FC4]">
          tenant {tenantSlug ?? '—'} · prepared by {email ?? '—'}
        </div>
      </div>
      <div className="ml-auto h-10 w-1 rounded-full" style={{ background: '#2FE6A0' }} />
    </div>
  )
}

function Stat({ label, value }: { label: string; value: string | null }) {
  return (
    <div className="rounded-lg border border-[#e5e1f0] p-3">
      <div className="text-[11px] text-[#6b6485]">{label}</div>
      <div className="font-mono text-[20px] font-medium">{value ?? '…'}</div>
    </div>
  )
}

function SectionTitle({ children }: { children: React.ReactNode }) {
  return (
    <h3 className="mb-2 mt-6 border-b border-[#e5e1f0] pb-1 text-[13px] font-medium first:mt-0">
      {children}
    </h3>
  )
}

function ExecutiveReport() {
  const evidence = useAuthedQuery(['evidence', 'queue'], (t) => api.listEvidence(t, { limit: 200 }))
  const events24h = useAuthedQuery(['events', '24h-total'], (t) =>
    api.listEvents(t, { start: isoHoursAgo(24), limit: 1 }),
  )
  const cases = useAuthedQuery(['cases', 'all'], (t) => api.listCases(t, { limit: 200 }))
  const coverage = useAuthedQuery(['mitre', 'coverage'], api.getMitreCoverage)

  const items = evidence.data?.items ?? []
  const open = items.filter((i) => i.status === 'open')
  const bySeverity = new Map<Severity, number>()
  for (const i of items) {
    const s = scoreSeverity(i.score)
    bySeverity.set(s, (bySeverity.get(s) ?? 0) + 1)
  }
  const maxSev = Math.max(...bySeverity.values(), 1)

  return (
    <div>
      <SectionTitle>Posture at a glance</SectionTitle>
      <div className="grid grid-cols-2 gap-3 md:grid-cols-4">
        <Stat label="Open alerts" value={evidence.data ? formatCount(open.length) : null} />
        <Stat
          label="Open cases"
          value={
            cases.data
              ? formatCount(cases.data.items.filter((c) => c.status !== 'closed').length)
              : null
          }
        />
        <Stat
          label="Events (24h)"
          value={events24h.data ? formatCount(events24h.data.total) : null}
        />
        <Stat
          label="Techniques detected"
          value={coverage.data ? formatCount(coverage.data.techniques_seen) : null}
        />
      </div>

      <SectionTitle>Alert severity distribution</SectionTitle>
      {(['critical', 'high', 'medium', 'low'] as Severity[]).map((sev) => {
        const n = bySeverity.get(sev) ?? 0
        return (
          <div key={sev} className="mb-1.5 flex items-center gap-2 text-[12px]">
            <span className="w-16 text-[#6b6485]">{sev}</span>
            <div className="h-3 flex-1 rounded bg-[#f1eef8]">
              <div
                className="h-3 rounded"
                style={{
                  width: `${(n / maxSev) * 100}%`,
                  background: SEV_HEX[sev],
                  printColorAdjust: 'exact',
                  WebkitPrintColorAdjust: 'exact',
                }}
              />
            </div>
            <span className="w-8 text-right font-mono">{n}</span>
          </div>
        )
      })}

      <SectionTitle>Top detected techniques</SectionTitle>
      <table className="w-full border-collapse text-[12px]">
        <thead>
          <tr className="text-left text-[#6b6485]">
            <th className="py-1 font-normal">Technique</th>
            <th className="py-1 font-normal">Name</th>
            <th className="py-1 text-right font-normal">Events</th>
          </tr>
        </thead>
        <tbody>
          {(coverage.data?.coverage ?? []).slice(0, 8).map((c) => (
            <tr key={c.technique_id} className="border-t border-[#e5e1f0]">
              <td className="py-1 font-mono">{c.technique_id}</td>
              <td className="py-1">{c.name ?? '—'}</td>
              <td className="py-1 text-right font-mono">{formatCount(c.event_count)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <SectionTitle>Cases</SectionTitle>
      <table className="w-full border-collapse text-[12px]">
        <tbody>
          {(cases.data?.items ?? []).slice(0, 10).map((c) => (
            <tr key={c.id} className="border-t border-[#e5e1f0]">
              <td className="py-1 font-mono">#{c.id}</td>
              <td className="max-w-64 truncate py-1">{c.title}</td>
              <td className="py-1">{c.severity}</td>
              <td className="py-1">{c.status}</td>
              <td className="py-1 text-right text-[#6b6485]">{c.assignee_email ?? '—'}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

function IncidentReport({ caseId }: { caseId: number }) {
  const c = useAuthedQuery(['case', caseId], (t) => api.getCase(t, caseId))
  if (!c.data) return <p className="py-8 text-center text-[13px] text-[#6b6485]">Loading case…</p>
  const d = c.data
  const techniques = [...new Set(d.evidence.flatMap((e) => e.technique_ids))]

  return (
    <div>
      <SectionTitle>Case</SectionTitle>
      <table className="w-full border-collapse text-[12px]">
        <tbody>
          {(
            [
              ['Title', d.title],
              ['Severity', d.severity],
              ['Status', d.status],
              ['Assignee', d.assignee_email ?? '—'],
              ['Opened', formatUtcDateTime(d.created_at)],
              ['Last activity', formatUtcDateTime(d.updated_at)],
            ] as const
          ).map(([k, v]) => (
            <tr key={k} className="border-t border-[#e5e1f0] first:border-0">
              <td className="w-32 py-1 text-[#6b6485]">{k}</td>
              <td className="py-1">{v}</td>
            </tr>
          ))}
        </tbody>
      </table>
      {d.description && <p className="mt-2 text-[12px]">{d.description}</p>}

      <SectionTitle>Techniques observed</SectionTitle>
      <p className="font-mono text-[12px]">{techniques.join(', ') || 'none recorded'}</p>

      <SectionTitle>Evidence ({d.evidence.length})</SectionTitle>
      <table className="w-full border-collapse text-[12px]">
        <thead>
          <tr className="text-left text-[#6b6485]">
            <th className="py-1 font-normal">Id</th>
            <th className="py-1 font-normal">Host</th>
            <th className="py-1 font-normal">Techniques</th>
            <th className="py-1 text-right font-normal">Score</th>
            <th className="py-1 text-right font-normal">Window end (UTC)</th>
          </tr>
        </thead>
        <tbody>
          {d.evidence.map((e) => (
            <tr key={e.id} className="border-t border-[#e5e1f0]">
              <td className="py-1 font-mono">#{e.id}</td>
              <td className="py-1 font-mono">{e.host_name ?? '—'}</td>
              <td className="py-1 font-mono">{e.technique_ids.join(', ')}</td>
              <td className="py-1 text-right font-mono">{e.score}</td>
              <td className="py-1 text-right font-mono">{formatUtcDateTime(e.window_end)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <SectionTitle>Analyst notes ({d.notes.length})</SectionTitle>
      {d.notes.length === 0 && <p className="text-[12px] text-[#6b6485]">No notes recorded.</p>}
      {d.notes.map((n) => (
        <div key={n.id} className="mb-2 border-l-2 pl-3" style={{ borderColor: '#2FE6A0' }}>
          <div className="text-[10px] text-[#6b6485]">
            {n.author_email ?? '—'} · {formatUtcDateTime(n.created_at)}
          </div>
          <p className="whitespace-pre-wrap text-[12px]">{n.body}</p>
        </div>
      ))}
    </div>
  )
}

function ComplianceReport() {
  const matrix = useAuthedQuery(['mitre', 'matrix'], api.getMitreMatrix)
  const coverage = useAuthedQuery(['mitre', 'coverage'], api.getMitreCoverage)

  if (!matrix.data || !coverage.data) {
    return <p className="py-8 text-center text-[13px] text-[#6b6485]">Loading coverage…</p>
  }

  const seen = new Set<string>()
  for (const c of coverage.data.coverage) {
    seen.add(c.technique_id)
    seen.add(c.technique_id.split('.')[0])
  }

  const perTactic = new Map<string, { total: number; covered: number }>()
  for (const t of matrix.data) {
    if (t.is_subtechnique) continue
    for (const tactic of t.tactics) {
      const entry = perTactic.get(tactic) ?? { total: 0, covered: 0 }
      entry.total += 1
      if (seen.has(t.technique_id)) entry.covered += 1
      perTactic.set(tactic, entry)
    }
  }
  const rows = [...perTactic.entries()].sort((a, b) => tacticRank(a[0]) - tacticRank(b[0]))
  const totals = rows.reduce(
    (acc, [, v]) => ({ total: acc.total + v.total, covered: acc.covered + v.covered }),
    { total: 0, covered: 0 },
  )

  return (
    <div>
      <SectionTitle>Detection coverage by tactic</SectionTitle>
      <p className="mb-3 text-[12px] text-[#6b6485]">
        Coverage = base techniques with at least one mapped detection in this tenant, against
        the full ATT&CK catalog ({formatCount(totals.total)} technique-tactic pairs).
      </p>
      {rows.map(([tactic, v]) => {
        const pct = v.total ? Math.round((v.covered / v.total) * 100) : 0
        return (
          <div key={tactic} className="mb-1.5 flex items-center gap-2 text-[12px]">
            <span className="w-44 text-[#6b6485]">{tacticLabel(tactic)}</span>
            <div className="h-3 flex-1 rounded bg-[#f1eef8]">
              <div
                className="h-3 rounded"
                style={{
                  width: `${pct}%`,
                  background: '#1D9E75',
                  printColorAdjust: 'exact',
                  WebkitPrintColorAdjust: 'exact',
                }}
              />
            </div>
            <span className="w-20 text-right font-mono">
              {v.covered}/{v.total} · {pct}%
            </span>
          </div>
        )
      })}
      <p className="mt-3 text-[12px]">
        Overall: <span className="font-mono">{totals.covered}</span> of{' '}
        <span className="font-mono">{totals.total}</span> covered (
        {totals.total ? Math.round((totals.covered / totals.total) * 100) : 0}%). Uncovered
        tactics are hunting-hypothesis candidates, not necessarily gaps in the estate.
      </p>
    </div>
  )
}
