"""initial schema: tenants, users, raw_events, normalized_events + RLS

Hand-written (not autogenerated) because RLS policies must ship in the
same revision as the tables they protect: there must be no deployable
state of ARGUS where tenant tables exist without isolation.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

# Every tenant-owned table gets identical RLS treatment.
TENANT_TABLES = ("users", "raw_events", "normalized_events")


def upgrade() -> None:
    # pgvector: not used by this revision, but enabling it here means every
    # environment that can run ARGUS is vector-ready before RAG arrives.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "tenants",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("name", sa.Text(), nullable=False, unique=True),
        sa.Column("slug", sa.Text(), nullable=False, unique=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )

    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False, server_default=sa.text("'analyst'")),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.UniqueConstraint("tenant_id", "email", name="uq_users_tenant_email"),
    )

    op.create_table(
        "raw_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), primary_key=True),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(), nullable=False),
        sa.Column(
            "received_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_index("ix_raw_events_tenant_received", "raw_events", ["tenant_id", "received_at"])

    op.create_table(
        "normalized_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), primary_key=True),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "raw_event_id",
            sa.BigInteger(),
            sa.ForeignKey("raw_events.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("event_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=True),
        sa.Column("severity", sa.SmallInteger(), nullable=True),
        sa.Column("host_name", sa.Text(), nullable=True),
        sa.Column("user_name", sa.Text(), nullable=True),
        sa.Column("src_ip", postgresql.INET(), nullable=True),
        sa.Column("dst_ip", postgresql.INET(), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_index(
        "ix_normalized_events_tenant_time", "normalized_events", ["tenant_id", "event_time"]
    )

    # --- Row-Level Security ---------------------------------------------
    # ENABLE turns RLS on; FORCE applies it even to the table OWNER (in dev
    # the app connects as the owner, and owners bypass RLS otherwise).
    # current_setting(..., true) returns NULL when app.current_tenant is
    # unset -> the policy evaluates to NULL -> DEFAULT DENY.
    # The WITH CHECK clause blocks writing rows for a different tenant.
    for table in TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        # NULLIF handles a pooled-connection gotcha: after a transaction that
        # used set_config ends, the GUC reverts to EMPTY STRING (not NULL) on
        # that connection, and ''::uuid raises a cast error. NULLIF turns ''
        # back into NULL -> policy evaluates NULL -> clean default deny.
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid) "
            f"WITH CHECK "
            f"(tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)"
        )


def downgrade() -> None:
    op.drop_table("normalized_events")
    op.drop_table("raw_events")
    op.drop_table("users")
    op.drop_table("tenants")
